### ISSUE TITLE
这个luci支持redsocks2的那个版本啊?

### ISSUE THREAD

**Issue by blog2i2j** [wltc2005/luci-app-redsocks2#1]
能请问一下, 这个luci支持配置哪个版本的redsocks2? 支持最新的0.67版本吗?

**Comment by wltc2005** [comment]
对的，支持。不过发现有时防火墙会影响redsocks2，需要重启服务

**Comment by blog2i2j** [comment]
收到, 感谢做这么好的项目.

**Comment by wltc2005** [comment]
重启服务那个也有办法解决，防火墙配置文件里是可以写自动重启redsocks2。

**Comment by blog2i2j** [comment]
防火墙重启redsocks2怎么搞定? 怎么检测redsocks2失效的?

**Comment by wltc2005** [comment]
检测就不必了，先建立一个sh比如redsocks2.include，作用是重启redsocks2。防火墙有个config，加一段类似于：
config include 'redsocks2'
        option type 'script'
        option path '/xxx/xxx/redsocks2.include'
        option reload '1'

**Comment by blog2i2j** [comment]
谢谢, 试试去
